### PR TITLE
fix: vertical line matching

### LINKED ISSUE #59: Unexpected behaviour | near-vertical line matching
Hi @JosiahParry , thanks for your package!

I have identified that in some instances `anime` would produce unexpected matches when joining geometries representing undirected networks. With help of Copilot I managed to identify the reason for this behaviour (I am far from being a Rust  developer). Here is reproducible example

```{r}
# For near-vertical lines, `atan(slope)` can flip between +89° and -89°
# depending on the sign of a sub-meter dx, causing truly parallel lines
# to appear ~178° apart and fail the angle tolerance check.

library(sf)
library(anime)

# --- Setup: two parallel near-vertical lines ---

# Target line: going north, leaning very slightly left
# dx = -0.5, dy = 50 -> slope ≈ -100 -> atan ≈ -89.4°
target <- st_sfc(st_linestring(matrix(
  c(
    100.0,
    0.0,
    99.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))

# Source A (CLOSE, ~2m away): leaning slightly RIGHT (opposite slope sign)
# dx = +0.5 -> slope ≈ +100 -> atan ≈ +89.4°
source_close <- st_sfc(st_linestring(matrix(
  c(
    102.0,
    0.0,
    102.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))

# Source B (FAR, ~10m away): leaning slightly left (same slope sign as target)
# dx = -0.5 -> slope ≈ -100 -> atan ≈ -89.4°
source_far <- st_sfc(st_linestring(matrix(
  c(
    110.0,
    0.0,
    109.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))

# distance from the target
st_distance(source_close, target)
#>      [,1]
#> [1,]    2
st_distance(source_far, target)
#>        [,1]
#> [1,] 9.9995

sources <- st_sf(
  label = c("close_but_rejected", "far_but_matched"),
  geometry = c(source_close, source_far)
)
target_sf <- st_sf(label = "target", geometry = target)

# The CLOSE source (2m away) is REJECTED, the FAR source (10m away) is MATCHED
m <- anime::anime(
  sources,
  target_sf,
  distance_tolerance = 15,
  angle_tolerance = 20
)
get_matches(m)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2          0               0               0
# -> Only source_id=2 (far, ~10m) matches. source_id=1 (close, ~2m) is rejected!

# Even with angle_tolerance = 89, the close source is still rejected
m2 <- anime::anime(
  sources,
  target_sf,
  distance_tolerance = 15,
  angle_tolerance = 89
)
get_matches(m2)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2          0               0               0
# -> Still only source_id=2. No angle_tolerance < 90 can fix this.

# --- Control: non-vertical lines work correctly ---
# Same parallel geometry but rotated so lines are ~45°, not near-vertical

target_nv <- st_sfc(st_linestring(matrix(
  c(
    0,
    0,
    40,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

source_nv_A <- st_sfc(st_linestring(matrix(
  c(
    2,
    0,
    42,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

source_nv_B <- st_sfc(st_linestring(matrix(
  c(
    -2,
    0,
    38,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

sources_nv <- st_sf(
  label = c("parallel_A", "parallel_B"),
  geometry = c(source_nv_A, source_nv_B)
)
target_nv_sf <- st_sf(label = "target", geometry = target_nv)

m3 <- anime::anime(
  sources_nv,
  target_nv_sf,
  distance_tolerance = 5,
  angle_tolerance = 20
)
get_matches(m3)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2         64               1               1
#> 2         1         1         64               1               1
# -> Both parallels match correctly when lines are not near-vertical.

# --- Plot ---
par(mar = c(4, 4, 4, 1))
plot(
  st_geometry(target_sf),
  xlim = c(97, 113),
  ylim = c(-5, 55),
  asp = 0.3,
  lwd = 3,
  lty = 2,
  col = "grey30"
)

plot(source_close, add = TRUE, lwd = 3, col = "tomato")
plot(source_far, add = TRUE, lwd = 3, col = "steelblue")

# --- Root cause ---
#
# The matching algorithm computes atan(slope) which maps to (-90°, +90°).
# For near-vertical lines, slope = dy/dx is very large, and the sign of
# dx determines whether atan returns +89° or -89°.
#
# Two genuinely parallel near-vertical lines can have opposite slope signs
# if one has dx = +0.5m and the other has dx = -0.5m, producing an apparent
# angle difference of ~178° and failing any reasonable angle tolerance.
#
# This also means that a line going in the OPPOSITE direction (reversed)
# along the same path may match preferentially over the correct parallel line,
# because reversing a line flips both dx and dy, which can restore the slope sign.
# 
```

Thanks again!

### PR DESCRIPTION
**Pull request by JosiahParry**
This PR closes #59 , supersedes #60 and supersedes #61. 

It fixes the near vertical line matching issue by using the absolute value of slopes rather than their actual calculated value. This is because there is no inherent sense of directionality that we can glean from the simple feature standard. A line that consists of C1, C2 is identical to a line composed of the coords C2, C1.

### CODE REVIEW

**Comment by JosiahParry** [comment]
@juanfonsecaLS1 @Robinlovelace @elifclaus please give this PR a go. 

The key thing is that it does not use the dot product as that changes the algorithm entirely. Rather, instead, we normalize the degrees to [0, 180) instead of taking the output of atan() directly which is [-90, 90].

I've added the reprex case as a test as well.

**Comment by JosiahParry** [comment]
bah, the build script is broken it seems :/

**Comment by JosiahParry** [comment]
Alrighty, ready for review! :) 
``` r
library(sf)
#> Linking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE
library(anime)

target <- st_sfc(st_linestring(matrix(
  c(
    100.0,
    0.0,
    99.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))

source_close <- st_sfc(st_linestring(matrix(
  c(
    102.0,
    0.0,
    102.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))

source_far <- st_sfc(st_linestring(matrix(
  c(
    110.0,
    0.0,
    109.5,
    50.0
  ),
  ncol = 2,
  byrow = TRUE
)))


sources <- st_sf(
  label = c("close_but_rejected", "far_but_matched"),
  geometry = c(source_close, source_far)
)
target_sf <- st_sf(label = "target", geometry = target)

m <- anime::anime(
  sources,
  target_sf,
  distance_tolerance = 15,
  angle_tolerance = 20
)
get_matches(m)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2     0.0000               0               0
#> 2         1         1    50.0025               1               1

m2 <- anime::anime(
  sources,
  target_sf,
  distance_tolerance = 15,
  angle_tolerance = 89
)
get_matches(m2)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2     0.0000               0               0
#> 2         1         1    50.0025               1               1

target_nv <- st_sfc(st_linestring(matrix(
  c(
    0,
    0,
    40,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

source_nv_A <- st_sfc(st_linestring(matrix(
  c(
    2,
    0,
    42,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

source_nv_B <- st_sfc(st_linestring(matrix(
  c(
    -2,
    0,
    38,
    50
  ),
  ncol = 2,
  byrow = TRUE
)))

sources_nv <- st_sf(
  label = c("parallel_A", "parallel_B"),
  geometry = c(source_nv_A, source_nv_B)
)
target_nv_sf <- st_sf(label = "target", geometry = target_nv)

m3 <- anime::anime(
  sources_nv,
  target_nv_sf,
  distance_tolerance = 5,
  angle_tolerance = 20
)
get_matches(m3)
#>   target_id source_id shared_len source_weighted target_weighted
#> 1         1         2   64.03124               1               1
#> 2         1         1   64.03124               1               1
```

<sup>Created on 2026-02-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

File: rust/src/lib.rs [hunk 1]
```diff
@@ -167,9 +167,9 @@ fn find_candidate_matches(
         let (i, x_slope) = cx.data;
         let (j, y_slope) = cy.data;
 
-        // convert calculated slopes to degrees
-        let x_deg = x_slope.atan().to_degrees();
-        let y_deg = y_slope.atan().to_degrees();
+        // convert calculated slopes to degrees normalize to 180
+        let x_deg = (x_slope.atan().to_degrees() + 180.0) % 180.0;
+        let y_deg = (y_slope.atan().to_degrees() + 180.0) % 180.0;
```
Comment (JosiahParry) [inline rust/src/lib.rs:172]: This is the only needed change

**Comment by Robinlovelace** [comment]
Looks like a good fix, thanks Josiah. Will give it a go and report any issues but general :+1:

File: rust/src/lib.rs (hunk 1 above)
Comment (Robinlovelace) [reply rust/src/lib.rs:172]: So simple! Good stuff.

**Comment by Robinlovelace** [comment]
Tested on dataset of London and works great for me, I do think `anime_join()` will be super useful but also know that my implementation in #58 has some issues, but that's a different matter. Let's get this merged!

Reprex I used to test this FYI:

```

```{r setup}
library(tidyverse)
library(sf)
```

```{r}
central_london <- c(-0.1276, 51.5074) |>
  st_point() |>
  st_sfc(crs = 4326) |>
  sf::st_buffer(5000)
library(osmextract)
net <- oe_get(
  central_london,
  query = "SELECT * FROM lines WHERE highway is NOT NULL",
  boundary = central_london,
  extra_tags = c("maxspeed")
)
net_cycle <- net |>
  filter(str_detect(highway, "cycleway")) |>
  transmute(
    id_cycleway = osm_id
  )
net_primary <- net |>
  filter(str_detect(highway, "primary")) |>
  transmute(
    id_primary = osm_id,
    maxspeed = as.numeric(gsub(" mph", "", maxspeed))
  )
nrow(net_cycle)
nrow(net_primary)
```

```{r}
joined1 <- anime::anime_join(
  net_primary,
  net_cycle
)
mapview::mapview(joined1["maxspeed_wt"])
```

**Review by Robinlovelace — APPROVED** [review]

**Comment by juanfonsecaLS1** [comment]
Thanks a lot @JosiahParry. I just ran a couple of tests and the issues is fixed.

**Comment by Robinlovelace** [comment]
Can we get this or a parallel fix merged @JosiahParry ? thanks
